import React from 'react';

const StatBar = ({ label, value, colorClass, reason, description }) => {
  const numValue = parseInt(value) || 0;
  
  return (
    <div className="mb-5 last:mb-0">
      <div className="flex justify-between mb-2 cursor-help">
        <span className="text-ethicLight/70 text-sm tracking-wide font-sans">
          {label}
        </span>
        <span className="text-ethicLight font-bold text-sm relative group/value cursor-help">
          {value}
          <div className="absolute bottom-full right-0 mb-2 hidden group-hover/value:block w-64 bg-ethicDark text-ethicLight text-xs font-normal rounded-lg p-3 shadow-xl border border-ethicLight/40 z-20 transition-opacity whitespace-normal text-left">
            <strong className="block text-ethicLight mb-1">Reason:</strong>
            {reason}
            <div className="absolute top-full right-4 -mt-px border-4 border-transparent border-t-ethicLight/40"></div>
          </div>
        </span>
      </div>
      <div className="w-full bg-ethicLight/5 rounded-full h-2.5 shadow-inner border border-ethicLight/10">
        <div 
          className="bg-ethicLight h-full rounded-full transition-all duration-1000 ease-out"
          style={{ width: `${numValue}%`, opacity: (numValue / 100) * 0.8 + 0.2 }}
        />
      </div>
    </div>
  );
};

export default function StatsBreakdown({ internet, internetReason, availability, availabilityReason, bias, biasReason, harmful, harmfulReason, originality, originalityReason, safety, safetyReason }) {
  return (
    <div className="card-law p-6">
      <h3 className="text-lg font-serif tracking-widest uppercase text-ethicLight mb-6 border-b border-ethicLight/20 pb-3">
        Stats Breakdown
      </h3>
      
      <StatBar 
        label="Internet Similarity" 
        value={internet} 
        reason={internetReason} 
        description="Pseudo-plagiarism indicator estimating if this exact phrasing exists online." 
      />
      <StatBar 
        label="Result Availability" 
        value={availability} 
        reason={availabilityReason} 
        description="Chance of finding the direct result generated by this prompt on the internet." 
      />
      <StatBar 
        label="Bias Risk" 
        value={bias} 
        reason={biasReason} 
        description="Likelihood of biased content, leaning, or unbalanced perspectives." 
      />
      <StatBar 
        label="Harmful Intent" 
        value={harmful} 
        reason={harmfulReason} 
        description="Potential for misuse, malicious behavior, or harmful outputs." 
      />
      <StatBar 
        label="Originality" 
        value={originality} 
        reason={originalityReason} 
        description="How uniquely and originally composed the content appears." 
      />
      <StatBar 
        label="Safety Score" 
        value={safety} 
        reason={safetyReason} 
        description="Overall confidence in the safety for public or academic use." 
      />
    </div>
  );
}
